# Generated by Django 6.0 on 2025-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('tex_file', models.FileField(upload_to='tex_sources/')),
                ('html_content', models.TextField(blank=True, editable=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
